import React, { Component } from 'react'

class Explication extends Component {
  render() {
    return (
      <div className="text-light">
        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut euismod, tellus in aliquet feugiat, orci nunc iaculis augue, id condimentum urna velit vel orci. Integer tincidunt ligula quis condimentum tempus. In facilisis elementum justo, sit amet imperdiet augue cursus ut. Vivamus quis turpis nisi. Nullam eget fringilla lacus, et condimentum ligula. In vitae nunc porttitor, fermentum neque nec, luctus nulla. Mauris vulputate vulputate sem non pulvinar. Suspendisse viverra lectus neque, sit amet sollicitudin dui aliquam et. In facilisis nisl diam, sed sollicitudin dolor commodo a. Vestibulum in dictum purus. Aenean quam nisi, sodales et sem ut, posuere porta nisl. Integer tincidunt magna vitae dolor pretium feugiat. Proin quam turpis, dapibus et lacus ac, euismod pellentesque tellus.</p>
        <p>Vestibulum a nisi sed risus consectetur sodales a ac lorem. Integer auctor metus dapibus, dignissim arcu eget, semper risus. Maecenas mi diam, tincidunt et consectetur quis, pharetra in massa. Vivamus leo dolor, tempor vel dolor quis, bibendum dictum arcu. Nam ac mi eget justo egestas sagittis. Fusce ac pharetra lacus. Vivamus posuere vel nisl quis laoreet. Donec at nisl euismod, scelerisque augue et, vestibulum dui. Nunc ac fringilla metus.</p>
        <p>Cras ut nibh nisi. Maecenas lectus leo, iaculis et tincidunt nec, dignissim congue velit. Suspendisse metus nisl, rhoncus ac porttitor ac, vehicula et nisl. In sit amet tellus purus. Morbi finibus dictum mi et sodales. Cras dictum vitae enim sit amet consequat. Ut porta interdum massa, sed sollicitudin lorem pharetra id. Donec quis leo mi. Duis suscipit sed risus eu vestibulum. Vestibulum in dolor vestibulum nunc vestibulum condimentum. Aenean in eros tempus, egestas lectus ac, finibus libero. Suspendisse malesuada, ex quis tempor vestibulum, sem felis semper elit, id molestie lacus diam sit amet odio. Proin dictum dictum lacus, porta rutrum turpis pulvinar at. Aliquam sollicitudin velit sit amet mi varius imperdiet. Ut condimentum, enim ac egestas mattis, metus metus suscipit enim, at tincidunt augue tortor id quam.</p>
        <p>Cras aliquet nisi congue ex convallis laoreet. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Proin pretium magna ligula, quis consequat quam mollis nec. Donec sollicitudin elementum ligula at tincidunt. Pellentesque sed nulla rhoncus, ultricies tellus vel, luctus justo. Vivamus ac augue at nisl sodales semper in a massa. Pellentesque id nisi quis massa luctus gravida vitae quis diam. Nunc aliquam, dolor vel cursus placerat, mauris purus maximus quam, ut pulvinar tellus urna fringilla lectus. Sed in purus vitae ligula ullamcorper rhoncus quis ut erat.</p>
        <p>Maecenas ut nisi non quam fringilla aliquet. Quisque vel iaculis lorem. Ut eleifend, ligula ac faucibus sollicitudin, nisl leo sollicitudin purus, sit amet volutpat turpis sapien vitae erat. Proin finibus nulla dapibus quam interdum, id viverra augue commodo. Proin quis lectus arcu. Integer enim eros, rutrum id commodo sit amet, malesuada non mauris. Donec lacinia bibendum felis ut ornare. Praesent pellentesque vehicula est et lobortis. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Cras vehicula a neque eget commodo. Aenean id libero ut augue scelerisque aliquet. Duis finibus aliquet dignissim. Donec sit amet est lorem. Cras tempor augue odio, in ultricies elit ornare vel.</p>
        <p>Donec accumsan sem a condimentum varius. Cras luctus et dui vel sodales. Praesent nec quam vitae dolor sagittis cursus. Aenean pharetra pharetra velit, vel faucibus leo. Curabitur ut justo urna. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Vestibulum viverra nibh in lacinia suscipit. Mauris nec lobortis ligula, et interdum urna. Pellentesque dictum purus sed fermentum tincidunt.</p>
        <p>Suspendisse potenti. Donec tempus, orci nec efficitur sodales, augue libero rhoncus ante, sed tristique est elit in risus. Suspendisse sed felis mi. Mauris eu justo tempor, consectetur nulla semper, rhoncus nisi. Nunc sollicitudin lacus dolor. Sed blandit porta sapien. Mauris mattis tempor nisl non pretium. Nam in sapien non massa ullamcorper pharetra a non purus. Mauris blandit dapibus neque sed accumsan.</p>
        <p>Donec rutrum tortor consequat, interdum ante a, posuere elit. Phasellus dolor tortor, cursus at eros in, tristique vulputate metus. Aliquam fermentum tincidunt mauris et commodo. Cras auctor lobortis nibh, a viverra urna placerat in. Vivamus sit amet est fringilla, ullamcorper velit quis, iaculis sapien. Suspendisse aliquam turpis risus, ut sollicitudin lorem auctor dignissim. Phasellus fringilla fringilla auctor. Duis in dui tincidunt, vestibulum tortor et, finibus ante.</p>
        <p>Fusce porta facilisis ex at gravida. Ut nibh nibh, facilisis ut faucibus ac, sagittis id dolor. Vestibulum eu dignissim est, ut blandit libero. Phasellus a nunc et sapien pulvinar gravida porta porttitor purus. Fusce vitae tortor elementum, commodo lacus ut, convallis diam. Donec ligula orci, aliquam sed ultricies et, efficitur nec dolor. Aenean condimentum, eros et vehicula euismod, est enim mattis felis, ac auctor est purus nec libero. In hac habitasse platea dictumst. Phasellus pulvinar commodo auctor. Sed porta ex mauris, in dictum tellus lobortis et. In sit amet diam lacus. Vestibulum ut lectus massa.</p>
        <p>Donec dignissim sodales malesuada. Phasellus gravida sem quis posuere accumsan. Sed eros massa, placerat non nisl quis, sodales sodales eros. Phasellus ac ipsum nec purus bibendum aliquam vel sed sapien. Donec finibus vestibulum nunc sed volutpat. Donec mauris sem, venenatis nec scelerisque eget, lobortis in orci. Nullam tristique velit sit amet semper sodales. Sed viverra lacus nec orci dictum finibus. Pellentesque feugiat bibendum augue, sagittis consectetur velit rhoncus ut. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae;</p>
      </div>
    )
  }
}

export default Explication;
