name: Tests

on:
  pull_request:
    branches:
      - master
    paths:
      - API/**

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
        run:
          working-directory: ./API
  
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Construction de l'image à partir du Dockerfile
        run: |
          docker build -t nom_image ./../GESTION BASE DE DONNEE

      - name: Démarrage du conteneur MySQL
        run: |
          docker run -d -p 3306:3306 -e MYSQL_ROOT_PASSWORD=Tennis1234@! nom_image
      
      - name: Attente du démarrage de MySQL
        run: |
          until docker exec $(docker ps -q --filter ancestor=nom_image) mysqladmin ping -h localhost --silent; do sleep 1; done

      - name: Run tests
        run: pytest