name: Tests

on:
  pull_request:
    branches:
      - master
    paths:
      - API/**

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
        run:
          working-directory: ./API
  
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Construction de l'image à partir du Dockerfile
        run: |
          cd ../GESTION\ BASE\ DE\ DONNEE
          docker build -t sql .

      - name: Démarrage du conteneur MySQL
        run: |
          cd ../GESTION\ BASE\ DE\ DONNEE
          docker run -d -p 3306:3306 --name sql sql

      - name: Wait for container to start
        run: |
          while [[ "$(docker ps -aqf "name=sql" --filter "health=healthy")" == "" ]]; do sleep 1; done

      - name: Run tests
        run: pytest