name: Pipeline CI/CD sur merge

on:
  push:
    branches:
      - master
    paths:
      - FRONTEND/volunteeze/**
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    defaults:
        run:
          working-directory: ./FRONTEND/volunteeze
    steps:
      - name: Import du code
        uses: actions/checkout@v3

      - name: Installation de Node
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      
      - name : Installation des dépendances et création du build
        run: npm install --production && npm run build
        env:
          REACT_APP_FIREBASE_API_KEY: ${{ secrets.REACT_APP_FIREBASE_API_KEY }}
          REACT_APP_FIREBASE_AUTH_DOMAIN: ${{ secrets.REACT_APP_FIREBASE_AUTH_DOMAIN }}
          REACT_APP_FIREBASE_PROJECT_ID: ${{ secrets.REACT_APP_FIREBASE_PROJECT_ID }}
          REACT_APP_FIREBASE_STORAGE_BUCKET: ${{ secrets.REACT_APP_FIREBASE_STORAGE_BUCKET }}
          REACT_APP_FIREBASE_MESSAGING_SENDER_ID: ${{ secrets.REACT_APP_FIREBASE_MESSAGING_SENDER_ID }}
          REACT_APP_FIREBASE_APP_ID: ${{ secrets.REACT_APP_FIREBASE_APP_ID }}
          REACT_APP_FIREBASE_MEASUREMENT_ID: ${{ secrets.REACT_APP_FIREBASE_MEASUREMENT_ID }}
          REACT_APP_GOOGLE_MAPS_API_KEY: ${{ secrets.REACT_APP_GOOGLE_MAPS_API_KEY }}
          EDITOR_UPSTREAM_RENDER_URL : ${{ secrets.EDITOR_UPSTREAM_RENDER_URL}}
      - name: Déploiement sur Firebase
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          entryPoint: ./FRONTEND/volunteeze
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_VOLUNTEEZE }}'
          channelId: live
          projectId: volunteeze