name: Deploy to Firebase Hosting on merge

on:
  push:
    branches:
      - master
    paths:
      - FRONTEND/volunteeze/**
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    defaults:
        run:
          working-directory: ./FRONTEND/volunteeze
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - run: ls
      - run: pwd

      - name: Install Node
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      
      - run: ls
      - run: pwd

      - run: npm install --production && npm run build

      - run: ls
      - run: pwd

      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_VOLUNTEEZE }}'
          channelId: live
          projectId: volunteeze
